
before_script:
    - git clone -b eric-fcv2-test -q https://gitlab.com/voxl-public/voxl-sdk/ci-tools

include:
  - project: 'voxl-public/voxl-sdk/ci-tools'
    file: '/pipeline-configs/common.yml'
  - project: 'voxl-public/voxl-sdk/ci-tools'
    file: '/pipeline-configs/qrb5165-px4.yml'

