#!/bin/sh
# PX4 commands need the 'px4-' prefix in bash.
# (px4-alias.sh is expected to be in the PATH)
. px4-alias.sh

CONFIG_FILE="/etc/modalai/voxl-px4.conf"
# read from conf file
GPS_SETTING=$(cat $CONFIG_FILE | grep -v '^*' | grep -v '/' | jq -r '.gps')
RC_SETTING=$(cat $CONFIG_FILE | grep -v '^*' | grep -v '/' | jq -r '.rc_mode')
IMU_SETTING=$(cat $CONFIG_FILE | grep -v '^*' | grep -v '/' | jq -r '.imu_rotation')
OSD_SETTING=$(cat $CONFIG_FILE | grep -v '^*' | grep -v '/' | jq -r '.osd')
CAL_SETTING=$(cat $CONFIG_FILE | grep -v '^*' | grep -v '/' | jq -r '.sensor_cal_src')

echo -e "\n*************************"
echo "GPS MODE: $GPS_SETTING"
echo "RC MODE: $RC_SETTING"
echo "IMU MODE: $IMU_SETTING"
echo "OSD MODE: $OSD_SETTING"
echo "DAEMON MODE: $DAEMON_SETTING"
echo "SENSOR CAL SRC: $CAL_SETTING"
echo -e "*************************\n"

# In order to just exit after starting the uorb / muorb modules define
# the environment variable MINIMAL_PX4. (e.g. export MINIMAL_PX4=1)
# This is useful for testing / debug where you may want to start drivers
# and modules manually from the px4 command shell
if [ ! -z $MINIMAL_PX4 ]; then
    /bin/echo "Running minimal script"
    exit 0
fi

# Sleep a little here. A lot happens when the uorb and muorb start
# and we need to make sure that it all completes successfully to avoid
# any possible race conditions.
/bin/sleep 1

param select /data/px4/param/parameters

# Load in all of the parameters that have been saved in the file
param load

# Start logging and use timestamps for log files when possible.
# Add the "-e" option to start logging immediately. Default is
# to log only when armed
logger start -t

/bin/sleep 1

# IMU (accelerometer / gyroscope)
if [ "$IMU_SETTING" != "NONE" ]; then
    /bin/echo "Starting IMU driver with rotation: $IMU_SETTING"
    qshell icm42688p start -s -R $IMU_SETTING
else
    qshell icm42688p start -s
fi


/bin/sleep 1

# Start Invensense ICP 101xx barometer built on to VOXL 2
qshell icp101xx start -I -b 5

# Magnetometer
if [ "$GPS_SETTING" == "MATEK" ]; then
    # Use this line for the magnetometer in the Matek Systems M8Q-5883 module
    /bin/echo "Starting Mateksys M8Q-5883 magnetometer"
    qshell qmc5883l start -R 10 -X -b 1
elif [ "$GPS_SETTING" == "HOLYBRO" ]; then
    # Use this line for the magnetometer in the Holybro GPS module
    /bin/echo "Starting Holybro magnetometer"
    qshell ist8310 start -R 10 -X -b 1
fi

# GPS
if [ "$GPS_SETTING" == "MATEK" ]; then
    # Use this gps start line instead for Matek Systems M8Q-5883 module
    /bin/echo "Starting Mateksys M8Q-5883 GPS"
    qshell gps start
elif [ "$GPS_SETTING" == "HOLYBRO" ]; then
    # Only the newer Holybro unit is supported on M0054
    /bin/echo "Starting Holybro GPS"
    qshell gps start -d 7 -b 115200
fi

# LED driver for the Pixhawk 4 GPS module
if [ "$GPS_SETTING" == "HOLYBRO" ]; then
    /bin/echo "Starting Holybro LED driver"
    qshell rgbled_ncp5623c start -X -b 1 -f 400 -a 56
fi

# We do not change the value of SYS_AUTOCONFIG but if it does not
# show up as used then it is not reported to QGC and we get a
# missing parameter error.
param touch SYS_AUTOCONFIG

# ESC driver
qshell modal_io start

/bin/sleep 1

if [ "$RC_SETTING" == "FAKE_RC_INPUT" ]; then
    /bin/echo "Starting fake RC driver"
    qshell rc_controller start
elif [ "$RC_SETTING" == "CRSF_RAW" ]; then
    /bin/echo "Starting CRSF RC driver"
    qshell crsf_rc start -d 7
elif [ "$RC_SETTING" == "CRSF_MAV" ]; then
    /bin/echo "Starting TBS crossfire RC - MAV Mode"
    qshell mavlink_rc_in start -m -p 7 -b 115200
elif [ "$RC_SETTING" == "SPEKTRUM" ]; then
    /bin/echo "Starting Spektrum RC"
    qshell spektrum_rc start
fi

/bin/sleep 1

# APM power monitor
qshell voxlpm start -X -b 2

# Start all of the processing modules on DSP
qshell sensors start
qshell ekf2 start
qshell mc_pos_control start
qshell mc_att_control start
qshell mc_rate_control start
qshell mc_hover_thrust_estimator start
qshell land_detector start multicopter
qshell manual_control start
qshell control_allocator start
qshell rc_update start
qshell commander start
qshell commander mode manual

/bin/sleep 1

# Start all of the processing modules on the applications processor
dataman start
navigator start

# This is needed for altitude and position hold modes
flight_mode_manager start

mavlink start -x -u 14556 -o 14557 -r 100000 -n lo -m onboard

# slow down some of the fastest streams in onboard mode
mavlink stream -u 14556 -s HIGHRES_IMU -r 10
mavlink stream -u 14556 -s ATTITUDE -r 10
mavlink stream -u 14556 -s ATTITUDE_QUATERNION -r 10
# speed up rc_channels
mavlink stream -u 14556 -s RC_CHANNELS -r 50

/bin/sleep 1

mavlink boot_complete

# Optional MSP OSD driver for DJI goggles
# This is only supported on M0054 (with M0125 accessory board)
if [ "$OSD_SETTING" == "enable" ]; then
    /bin/echo "Starting OSD driver"
    msp_osd start -d /dev/ttyHS1
fi
