#!/bin/bash
################################################################################
# Copyright 2022 ModalAI Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# 4. The Software is used solely in conjunction with devices provided by
#    ModalAI Inc.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
################################################################################

NAME="voxl-px4"
SERVICE_FILE="${NAME}.service"
USER=$(whoami)


print_usage () {
	echo ""
	echo "Start wizard with prompts:"
	echo "voxl-configure-px4"
	echo ""
	echo "Shortcut configuration arguments for scripted setup."
	echo ""
	echo "voxl-configure-px4 disable"
	echo "voxl-configure-px4 enable"
    echo "voxl-configure-px4 default"
    echo "voxl-configure-px4 sentinel"
    echo "voxl-configure-px4 fpv"
	echo ""
	echo "show this help message:"
	echo "voxl-configure-px4 help"
	echo ""
	exit 0
}

disable_service_and_exit () {
	echo "disabling ${NAME} systemd service"
	systemctl disable ${SERVICE_FILE}
	echo "stopping ${NAME} systemd service"
	systemctl stop ${SERVICE_FILE}
	echo "Done configuring ${NAME}"
	exit 0
}

enable_service_and_exit () {
	echo "enabling  ${NAME} systemd service"
	systemctl enable  ${SERVICE_FILE}
	echo "starting  ${NAME} systemd service"
	systemctl restart  ${SERVICE_FILE}
	echo "Done configuring ${NAME}"
	exit 0
}

################################################################################
## actual start of execution, handle optional arguments first
################################################################################

## sanity checks
if [ "${USER}" != "root" ]; then
	echo "Please run this script as root"
	exit 1
fi

## convert argument to lower case for robustness
arg=$(echo "$1" | tr '[:upper:]' '[:lower:]')

## parse arguments
case ${arg} in
	"")
		echo "Starting Wizard"
		;;
	"h"|"-h"|"help"|"--help")
		print_usage
		exit 0
		;;
	"disable")
		disable_service_and_exit
		;;
	"enable")
		enable_service_and_exit
		;;
    "default")
        cp /etc/voxl-px4.service /etc/systemd/system/voxl-px4.service
        systemctl daemon-reload
		enable_service_and_exit
		;;
    "d0006")
        cp /etc/voxl-px4.service /etc/systemd/system/voxl-px4.service
        systemctl daemon-reload
		enable_service_and_exit
        ;;
    "sentinel")
        cp /etc/voxl-px4.service /etc/systemd/system/voxl-px4.service
        systemctl daemon-reload
		enable_service_and_exit
		;;
    "d0008")
        cp /etc/voxl-px4.service-fpv /etc/systemd/system/voxl-px4.service
        systemctl daemon-reload
		enable_service_and_exit
		;;
    "fpv")
        cp /etc/voxl-px4.service-fpv /etc/systemd/system/voxl-px4.service
        systemctl daemon-reload
		enable_service_and_exit
		;;
	*)
		echo "invalid option"
		print_usage
		exit 1
esac

echo " "
echo "Which configuration of voxl-px4 would you like to use?"
echo ""
echo "default                use default settings"
echo "sentinel               use settings for Sentinel"
echo "fpv                    use settings for FPV"
echo ""
select opt in "default" "sentinel" "fpv"; do
case $opt in
default )
    cp /etc/voxl-px4.service /etc/systemd/system/voxl-px4.service
    systemctl daemon-reload
	break;;
sentinel )
	cp /etc/voxl-px4.service /etc/systemd/system/voxl-px4.service
    systemctl daemon-reload
	break;;
fpv )
	cp /etc/voxl-px4.service-fpv /etc/systemd/system/voxl-px4.service
    systemctl daemon-reload
	break;;
*)
	echo "invalid option"
	esac
done

# ask if the user wants the service enabled or not
echo " "
echo "Do you want to enable the voxl-px4 service to be"
echo "enabled on boot?"
select opt in "yes" "no"; do
case $opt in
yes )
	echo " "
	enable_service_and_exit
	break;;
no )
	disable_service_and_exit
	break;;
*)
	echo "invalid option"
	esac
done

# all done!
enable_service_and_exit
