#!/bin/bash
################################################################################
# Copyright 2022 ModalAI Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# 4. The Software is used solely in conjunction with devices provided by
#    ModalAI Inc.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
################################################################################

NAME="voxl-px4"
SERVICE_FILE="${NAME}.service"
CONFIG_FILE="/etc/modalai/${NAME}.conf"
USER=$(whoami)

print_usage () {
	echo ""
	echo "Start wizard with prompts:"
	echo "voxl-configure-px4"
	echo ""
	echo "Shortcut configuration arguments for scripted setup."
	echo ""
	echo "voxl-configure-px4 disable"
	echo "voxl-configure-px4 enable"
    echo "voxl-configure-px4 factory_enable"
	echo "voxl-configure-px4 d0005_v2"
	echo "voxl-configure-px4 starling_v2"
	echo "voxl-configure-px4 d0006_v1"
    echo "voxl-configure-px4 sentinel_v1"
    echo "voxl-configure-px4 d0008"
    echo "voxl-configure-px4 fpv_revB"
	echo ""
	echo "show this help message:"
	echo "voxl-configure-px4 help"
	echo ""
}

## set most parameters which don't have quotes in json
set_param () {
	if [ "$#" != "2" ]; then
		echo "set_param expected 2 args"
		exit 1
	fi

	# remove quotes if they exist
	var=$1
	var="${var%\"}"
	var="${var#\"}"
	val=$2
	val="${val%\"}"
	val="${val#\"}"

	sed -E -i "/\"$var\":/c\	\"$var\":	$val," ${CONFIG_FILE}
}

## set string parameters which need quotes in json
set_param_string () {
	if [ "$#" != "2" ]; then
		echo "set_param_string expected 2 args"
		exit 1
	fi
	var=$1
	var="${var%\"}"
	var="${var#\"}"
	sed -E -i "/\"$var\":/c\	\"$var\":	\"$2\"," ${CONFIG_FILE}
}

disable_service_and_exit () {
	echo "disabling ${NAME} systemd service"
	systemctl disable ${SERVICE_FILE}
	echo "stopping ${NAME} systemd service"
	systemctl stop ${SERVICE_FILE}
	echo "Done configuring ${NAME}"
	exit 0
}

enable_service_and_exit () {
	echo "enabling  ${NAME} systemd service"
	systemctl enable  ${SERVICE_FILE}
	echo "starting  ${NAME} systemd service"
	systemctl restart  ${SERVICE_FILE}
	echo "Done configuring ${NAME}"
	exit 0
}

reset_config_file_to_default () {
	echo "wiping old config file"
	rm -rf ${CONFIG_FILE}
	${NAME} -c
}

################################################################################
## actual start of execution, handle optional arguments first
################################################################################

## sanity checks
if [ "${USER}" != "root" ]; then
	echo "Please run this script as root"
	exit 1
fi

## convert argument to lower case for robustness
arg=$(echo "$1" | tr '[:upper:]' '[:lower:]')

## parse arguments
case ${arg} in
	"")
		echo "Starting Wizard"
		;;
	"h"|"-h"|"help"|"--help")
		print_usage
		exit 0
		;;
	"disable")
		disable_service_and_exit
		;;
	"enable")
		enable_service_and_exit
		;;
    "factory_enable")
		reset_config_file_to_default
		enable_service_and_exit
		;;
	"d0005_v2"|"starling_v2")
		reset_config_file_to_default
		set_param_string gps MATEK
		set_param_string rc CRSF_RAW
		enable_service_and_exit
		;;
    "d0006_v1"|"sentinel_v1")
		reset_config_file_to_default
		set_param_string gps HOLYBRO
		set_param_string rc SPEKTRUM
		enable_service_and_exit
        ;;
    "d0008"|"fpv_revB")
		reset_config_file_to_default
		set_param_string gps MATEK
		set_param_string rc CRSF_RAW
		set_param_string imu_rotation 4
		set_param_string osd enable
		enable_service_and_exit
		;;
	*)
		echo "invalid option: $arg"
		exit 1
esac

################################################################################
## no optional arguments, start config wizard prompts
################################################################################

echo " "
echo "Do you want to reset the config file to factory defaults?"
select opt in "yes" "no"; do
case $opt in
yes )
	reset_config_file_to_default
	break;;
no )
	echo "loading and updating config file with ${NAME} -c"
	${NAME} -c
	break;;
*)
	echo "invalid option"
	esac
done


echo " "
echo "Which configuration of voxl-px4 would you like to use?"
echo ""
echo "factory_enable         use default factory settings"
echo "sentinel               use settings for Sentinel"
echo "fpv                    use settings for FPV"
echo ""
select opt in "factory_enable" "sentinel" "fpv"; do
case $opt in
factory_enable )
	break;;
sentinel )
	break;;
fpv )
	break;;
*)
	echo "invalid option"
	esac
done

# ask if the user wants the service enabled or not
echo " "
echo "Do you want to enable the voxl-px4 service to be"
echo "enabled on boot?"
select opt in "yes" "no"; do
case $opt in
yes )
	echo " "
	enable_service_and_exit
	break;;
no )
	disable_service_and_exit
	break;;
*)
	echo "invalid option"
	esac
done

# all done!
enable_service_and_exit
